config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :gossip
  resources :users, only: [:show, :new, :create]
  resources :author, only: [:show]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :city, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  get '/welcome/:first_name' => 'home#welcome', as: 'welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
  end
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :gossip, optional: true
  has_many :likes
  has_many :children_comments, class_name: 'Comment', foreign_key: 'parent_comment_id', dependent: :destroy
  belongs_to :parent_comment, class_name: 'Comment', optional: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates_length_of :title, within: 3..14, too_long: 'Titre trop long', too_short: 'Titre trop court'
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment, optional: true
  belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossip = @city.gossips
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def new
    @gossip = Gossip.new
  end

  def index
    @gossips = Gossip.all.sort_by(&:created_at)
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      flash[:notice] = 'Potin sauvegardé'
      redirect_to gossip_path(@gossip.id)
    else
      flash[:alert] = 'Erreur : impossible de sauvegarder le potin'
      render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.all
    @city = City.all
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to '/welcome/test'
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
  end
  def index
    
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      flash[:notice] = 'Potin sauvegardé'
      redirect_to gossip_path(@gossip.id)
    else
      flash[:alert] = 'Erreur : impossible de sauvegarder le potin'
      render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.all
    @city = City.all
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, :id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home 
  end

  def welcome
    @first_name = params[:first_name]
    @gossip = Gossip.all
    @user = User.all
    # @gossips = Gossip.includes(:user).all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :password, :city_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/edit.html.erb
<div class="container">
  <h1 class="my-4">Editer l'article</h1>

  <%= form_for @gossip do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control mb-3' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', rows: 5, placeholder: "Contenu de l'article" %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Modifier l'article", class: "btn btn-success mt-5" %>
    </div>
  <% end %>
</div>

app/views/gossip/index.html.erb
<h1 class="text-center mt-4">Bienvenue <%= @first_name %></h1>
<%= link_to 'Créer un nouveau potin', new_gossip_path, class: "btn btn-success ms-5 disabled" %>

<h2 class="text-center my-5">Voici la liste des potins :</h2>
<div class="d-flex justify-content-between text-center">
  <div class="row">
    <% @gossip.each_slice(3) do |gossips| %>
      <% gossips.each do |gossip| %>
        <div class="d-flex justify-content-center col-md-4 col-sm-6 my-4">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <p class="card-text">Potin n°: <%= gossip.id %></p>
              <h5 class="card-title">Titre: <%= gossip.title %></h5> 
                <% if gossip.user %>
                  <p class="card-text">Auteur: <%= gossip.user.first_name %></p>
                <% end %>
              <%= link_to 'Voir le potin', gossip_path(gossip), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/gossip/new.html.erb
<div class="container">
  <h1 class="text-center mt-5">Créer un potin</h1>

  <%= form_for @gossips |f| %>
    <div class="row my-3">
      <div class="mb-2">
        <%= f.label :title %>
      </div>
      <div class="">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="row my-3">
      <div class="mb-2">
        <%= f.label :content %>
      </div>
      <div class="">
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
      </div>
    </div>

    <div class="form-group text-center">
      <%= link_to "Retour aux gossips", :back, class: "btn btn-sm btn-secondary mr-3" %>
      <%= f.submit "Ajouter le gossip", class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/gossip/show.html.erb
<h1 class="text-center">Vous voici sur la page du potin n°<%= @gossip.id %></h1>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mb-3">Titre : <%= @gossip.title%></h2>
      <p class="mb-3">Ce que raconte ce Gossip :</p>
      <div class="card p-3">
        <%= @gossip.content%>
      </div>
      <p class="my-3">Ville de l'auteur : <%= @user.find(@gossip.user_id).city.name %></p>
      <br>
      <% date = @gossip.created_at %>
      <p class="text-muted mt-3">Créé le : <%= date.strftime("%d-%m-%Y à %H:%M") %> par <%= @user.find(@gossip.user_id).first_name %> <%= @user.find(@gossip.user_id).last_name %></p>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center">
      <%= link_to "Retour aux gossips", :back, class: "btn btn-secondary" %>
      <%= link_to "Profil de l'auteur", author_path(@user.find(@gossip.user_id)), class: "btn btn-primary" %>
      <%= link_to "Editer le gossip", edit_gossip_path(@gossip), class: "btn btn-warning" %>
      <%= button_to "Supprimer le gossip", gossip_path(@gossip), method: :delete, class: "btn btn-danger mt-3" %>
    </div>
    </div>
  </div>
</div>

app/views/gossip/view.html.erb
<h1>Potin n°<%= @gossip.id %></h1>

app/views/gossips/new.html.erb
<div class="container">
  <h1 class="text-center mt-5">Créer un potin</h1>

  <%= form_for @gossip do |f| %>
    <div class="row my-3">
      <div class="mb-2">
        <%= f.label :title %>
      </div>
      <div class="">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="row my-3">
      <div class="mb-2">
        <%= f.label :content %>
      </div>
      <div class="">
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
      </div>
    </div>

    <div class="form-group text-center">
      <%= link_to "Retour aux gossips", :back, class: "btn btn-sm btn-secondary mr-3" %>
      <%= f.submit "Ajouter le gossip", class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/gossips/show.html.erb
<h1 class="text-center">Vous voici sur la page du potin n°<%= @gossip.id %></h1>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mb-3">Titre : <%= @gossip.title%></h2>
      <p class="mb-3">Ce que raconte ce Gossip :</p>
      <div class="card p-3">
        <%= @gossip.content%>
      </div>
      <p class="my-3">Ville de l'auteur : <%= @user.find(@gossip.user_id).city.name %></p>
      <br>
      <% date = @gossip.created_at %>
      <p class="text-muted mt-3">Créé le : <%= date.strftime("%d-%m-%Y à %H:%M") %> par <%= @user.find(@gossip.user_id).first_name %> <%= @user.find(@gossip.user_id).last_name %></p>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center">
      <%= link_to "Retour aux gossips", :back, class: "btn btn-secondary" %>
      <%= link_to "Profil de l'auteur", author_path(@user.find(@gossip.user_id)), class: "btn btn-primary" %>
    </div>
  </div>
</div>