config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :gossip
  resources :users, only: [:show, :new, :create]
  resources :author, only: [:show]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :city, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  get '/welcome/:first_name' => 'home#welcome', as: 'welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
  end
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :gossip, optional: true
  has_many :likes
  has_many :children_comments, class_name: 'Comment', foreign_key: 'parent_comment_id', dependent: :destroy
  belongs_to :parent_comment, class_name: 'Comment', optional: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates_length_of :title, within: 3..14, too_long: 'Titre trop long', too_short: 'Titre trop court'
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment, optional: true
  belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossip = @city.gossips
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home 
  end

  def welcome
    @first_name = params[:first_name]
    @gossip = Gossip.all
    @user = User.all
    # @gossips = Gossip.includes(:user).all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="align-items-center text-center mx-auto mt-5">
  <h1>Bienvenue sur The gossip Project</h1>
  <p>Pour visualiser les informations, merci de te connecter en ajoutant /welcome/ce_que_tu_veux</p>
  <%= link_to "Se connecter mode dev", '/welcome/test', class: 'btn btn-success disabled' %>
</div>

app/views/home/welcome.html.erb
<h1 class="text-center mt-4">Bienvenue <%= @first_name %></h1>
<%= link_to 'Créer un nouveau potin', new_gossip_path, class: "btn btn-success ms-5 disabled" %>

<h2 class="text-center my-5">Voici la liste des potins :</h2>
<div class="d-flex justify-content-between text-center">
  <div class="row">
    <% @gossip.each_slice(3) do |gossips| %>
      <% gossips.each do |gossip| %>
        <div class="d-flex justify-content-center col-md-4 col-sm-6 my-4">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <p class="card-text">Potin n°: <%= gossip.id %></p>
              <h5 class="card-title">Titre: <%= gossip.title %></h5> 
                <% if gossip.user %>
                  <p class="card-text">Auteur: <%= gossip.user.first_name %></p>
                <% end %>
              <%= link_to 'Voir le potin', gossip_path(gossip), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/show/show.html.erb
<h1 class="text-center">Vous voici sur la page du potin n°<%= @show.id %></h1>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mb-3">Titre : <%= @show.title%></h2>
      <p class="mb-3">Ce que raconte ce Gossip :</p>
      <div class="card p-3">
        <%= @show.content%>
      </div>
      <br>
      <% date = @show.created_at %>
      <p class="text-muted mt-3">Créé le : <%= date.strftime("%d-%m-%Y à %H:%M") %> par <%= @user.find(@show.user_id).first_name %> <%= @user.find(@show.user_id).last_name %></p>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center">
      <%= link_to "Retour aux gossips", :back, class: "btn btn-secondary" %>
      <%= link_to "Profil de l'auteur", author_path(@user.find(@show.user_id)), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/team/index.html.erb
<div class="align-items-center text-center mx-auto mt-5">
  <h1>Qui est dans la team ?</h1>
  <p>Chacun a fait son projet</p>
</div>

app/views/team/team.html.erb
<div class="align-items-center text-center mx-auto mt-5">
  <h1>Qui est dans la team ?</h1>
  <p>Chacun a fait son projet</p>
</div>