config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :gossip
  resources :users, only: [:show, :new, :create]
  resources :author, only: [:show]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :city, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  get '/welcome/:first_name' => 'home#welcome', as: 'welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
  end
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :gossip, optional: true
  has_many :likes
  has_many :children_comments, class_name: 'Comment', foreign_key: 'parent_comment_id', dependent: :destroy
  belongs_to :parent_comment, class_name: 'Comment', optional: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates_length_of :title, within: 3..14, too_long: 'Titre trop long', too_short: 'Titre trop court'
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment, optional: true
  belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossip = @city.gossips
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home 
  end

  def welcome
    @first_name = params[:first_name]
    @gossip = Gossip.all
    @user = User.all
    # @gossips = Gossip.includes(:user).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" type="css" href="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


<%= stylesheet_link_tag "application" %> 

    <%= javascript_importmap_tags %>
  </head>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark"">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="<%= root_path %>">Accueil</a>
        <a class="nav-link" href="<%= team_index_path %>">La team</a>
        <a class="nav-link" href="<%= contact_index_path %>">Contact</a>
        <a class="nav-link" href="<%= new_user_path %>">S'inscrire</a>
        <a class="nav-link me-5" href="<%= new_session_path %>">Se connecter</a>
        <%
=begin%>
 <% if current_user %>
          <%= button_to "Déconnexion", session_path(@user), method: :delete, class: 'btn btn-danger ms-5' %>
        <% end %> 
<%
=end%>
      </div>
    </div>
  </div>
  </nav>

  <body>
    <%= render 'shared/flash' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>

  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>